Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [3]:
import numpy as np
array = np.random.randint(1, 101, (3, 3))
print(array)

[[ 69  13  96]
 [ 65  56 100]
 [ 12  93  41]]


In [5]:
array.T

array([[ 69,  65,  12],
       [ 13,  56,  93],
       [ 96, 100,  41]])

Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [8]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x= arr.reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
x.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [13]:
a = np.random.rand(4,4)
a

array([[0.94857055, 0.14413036, 0.13334   , 0.84253092],
       [0.87623793, 0.57487654, 0.50079492, 0.79782122],
       [0.07988556, 0.83397037, 0.68828944, 0.79023505],
       [0.60223319, 0.92170332, 0.76571815, 0.81421288]])

In [14]:
b = np.zeros((6,6))
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
b[1:-1, 1:-1] = a
b

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.94857055, 0.14413036, 0.13334   , 0.84253092,
        0.        ],
       [0.        , 0.87623793, 0.57487654, 0.50079492, 0.79782122,
        0.        ],
       [0.        , 0.07988556, 0.83397037, 0.68828944, 0.79023505,
        0.        ],
       [0.        , 0.60223319, 0.92170332, 0.76571815, 0.81421288,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [19]:
array = np.arange(10, 61, 5)
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [20]:
array = np.array(['python', 'numpy', 'pandas'])
array

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [22]:
x = np.char.upper(array)
x

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [23]:
y = np.char.lower(array)
y

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [24]:
z = np.char.title(array)
z

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [25]:
w = np.char.capitalize(array)
w

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [26]:
x = np.array(['python', 'numpy', 'pandas'])
x

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [27]:
y = np.char.join(' ', x)
y

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [28]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [29]:
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [30]:
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [31]:
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [32]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [33]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.diag(x)

array([1., 1., 1., 1., 1.])

Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [36]:
array = np.random.randint(0, 1001, 100)
array
def is_prime(num):
    if num <= 1:
      return False
    if num == 2:
      return True
    if num % 2 == 0:
      return False
    for i in range(3, num, 2):
      if num % i == 0:
        return False
    return True

prime_numbers = []
for num in array:
  if is_prime(num):
    prime_numbers.append(num)
print(prime_numbers)


[557, 17, 383, 857, 601, 521, 499, 199, 373, 661, 467, 89, 463, 107]


Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [37]:
daily_temp = np.random.randint(20, 40, 30)
daily_temp

array([34, 24, 32, 30, 34, 37, 20, 25, 20, 23, 37, 20, 29, 32, 20, 25, 25,
       39, 32, 27, 36, 24, 22, 38, 32, 35, 37, 27, 36, 23])

In [38]:
weekly_temp = daily_temp.reshape(5, 6)
weekly_temp

array([[34, 24, 32, 30, 34, 37],
       [20, 25, 20, 23, 37, 20],
       [29, 32, 20, 25, 25, 39],
       [32, 27, 36, 24, 22, 38],
       [32, 35, 37, 27, 36, 23]])

In [39]:
weekly_temp.mean(axis=1)

array([31.83333333, 24.16666667, 28.33333333, 29.83333333, 31.66666667])